name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'yes' to confirm destruction of infrastructure."
        required: true
        default: "no"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check if destruction is confirmed
        if: ${{ github.event.inputs.confirm != 'yes' }}
        run: |
          echo "Destruction not confirmed. Exiting."
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7 

      - name: Terraform Init with S3 Backend
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          Terraform Init -backend-config="bucket=threat-model-bucket" \
                         -backend-config="key=state" \
                         -backend-config="region=eu-west-2" \
                         -backend-config="encrypt=true"

      - name: Terraform Destroy
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: Terraform Destroy -auto-approve
